name: Metrics
on:
  schedule: [{cron: "0 13 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_padding: 10%, 10%      
          config_display: large
          
          user: dingonewen
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York 
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, jupyter notebook
          plugin_languages_details: bytes-size, percentage
          
          plugin_lines: yes
